export const allCategories = [
   'Electronics',
   'Clothing',
   'Home & Kitchen',
   'Sports & Outdoors',
   'Books',
   'Beauty & Personal Care',
   'Toys & Games',
   'Automotive',
   'Health',
]
export const allSize = ['XS', 'S', 'M', 'L', 'XL', 'XXL']

export const allColors = [
   'White',
   'Black',
   'Red',
   'Blue',
   'Green',
   'Yellow',
   'Orange',
   'Purple',
   'Pink',
   'Gray',
   'Brown',
   'Beige',
   'Navy',
   'Turquoise',
   'Lime',
   'Olive',
   'Teal',
   'Sky',
   'Plum',
   'Fuchsia',
   'Lavender',
   'Magenta',
   'Rose',
   'Amber',
]
