
export const allSize = ['XS', 'S', 'M', 'L', 'XL', 'XXL']

export const allColors = [
   'White',
   'Black',
   'Red',
   'Blue',
   'Green',
   'Yellow',
   'Orange',
   'Purple',
   'Pink',
   'Gray',
   'Brown',
   'Beige',
   'Navy',
   'Turquoise',
   'Lime',
   'Olive',
   'Teal',
   'Sky',
   'Plum',
   'Fuchsia',
   'Lavender',
   'Magenta',
   'Rose',
   'Amber',
]

export const allCategories = {
   Fashion: {
      Men: ['Clothing', 'Shoes', 'Watches', 'Accessories'],
      Women: ['Clothing', 'Shoes', 'Jewelry', 'Bags', 'Accessories'],
      Kids: ['Clothing', 'Shoes', 'Accessories'],
      Accessories: ['Sunglasses', 'Bags', 'Belts', 'Hats', 'Jewelry'],
   },
   Electronics: {
      'Mobile Phones': ['Smartphones', 'Basic Phones', 'Phone Accessories'],
      Laptops: ['Ultrabooks', 'Gaming Laptops', 'Business Laptops', 'Laptop Accessories'],
      Cameras: ['DSLR', 'Mirrorless', 'Point & Shoot', 'Camera Accessories'],
      'Television & Audio': ['LED TVs', 'Smart TVs', 'Sound Systems', 'Headphones'],
      'Wearable Technology': ['Smartwatches', 'Fitness Trackers', 'VR Headsets'],
      'Home Appliances': ['Refrigerators', 'Washing Machines', 'Microwaves', 'Vacuum Cleaners'],
   },
   'Home & Kitchen': {
      Furniture: ['Living Room Furniture', 'Bedroom Furniture', 'Office Furniture'],
      'Kitchen Appliances': ['Microwaves', 'Ovens', 'Coffee Makers', 'Blenders'],
      'Home Decor': ['Wall Art', 'Lighting', 'Rugs', 'Curtains'],
      Bedding: ['Bedsheets', 'Pillows', 'Mattresses', 'Blankets'],
      'Tools & DIY': ['Hand Tools', 'Power Tools', 'Gardening Tools'],
   },
   'Beauty & Personal Care': {
      Skincare: ['Moisturizers', 'Cleansers', 'Serums', 'Sunscreen'],
      'Hair Care': ['Shampoos', 'Conditioners', 'Hair Styling', 'Hair Color'],
      Fragrances: ['Perfume', 'Body Sprays', 'Cologne'],
      Makeup: ['Foundation', 'Lipstick', 'Eyeshadow', 'Mascara'],
   },
   'Sports & Outdoors': {
      'Fitness Equipment': ['Treadmills', 'Dumbbells', 'Yoga Mats', 'Resistance Bands'],
      'Outdoor Gear': ['Camping Tents', 'Sleeping Bags', 'Backpacks', 'Climbing Gear'],
      Sportswear: ['Activewear', 'Sports Shoes', 'Sweatbands'],
      'Camping & Hiking': ['Tents', 'Hiking Shoes', 'Trekking Poles', 'Portable Stoves'],
   },
   Books: {
      Fiction: ['Science Fiction', 'Fantasy', 'Mystery', 'Romance'],
      'Non-fiction': ['Biographies', 'Self-Help', 'History', 'Science'],
      "Children's Books": ['Picture Books', 'Early Readers', 'Young Adult'],
      Textbooks: ['School Textbooks', 'College Textbooks', 'Reference Books'],
      'E-books': ['Fiction E-books', 'Non-fiction E-books', 'Educational E-books'],
   },
   'Toys & Games': {
      'Action Figures': ['Superheroes', 'Movie Characters', 'Video Game Characters'],
      Puzzles: ['Jigsaw Puzzles', 'Brain Teasers', '3D Puzzles'],
      'Board Games': ['Classic Games', 'Strategy Games', 'Card Games'],
      Dolls: ['Barbie Dolls', 'Baby Dolls', 'Collectible Dolls'],
      'Outdoor Toys': ['Bicycles', 'Scooters', 'Playhouses', 'Water Toys'],
   },
   Automotive: {
      'Car Accessories': ['Seat Covers', 'Floor Mats', 'Air Fresheners', 'Car Electronics'],
      'Motorcycle Gear': ['Helmets', 'Jackets', 'Gloves', 'Boots'],
      'Tools & Equipment': ['Wrenches', 'Socket Sets', 'Car Jacks'],
      'Car Care': ['Car Wash', 'Polish', 'Waxes', 'Cleaning Kits'],
   },
   Health: {
      Supplements: ['Vitamins', 'Protein Powders', 'Herbal Supplements'],
      'Medical Equipment': ['Blood Pressure Monitors', 'Thermometers', 'First Aid Kits'],
      Fitness: ['Exercise Bikes', 'Treadmills', 'Resistance Bands'],
      'Personal Hygiene': ['Soap', 'Sanitizers', 'Toothpaste', 'Deodorants'],
   },
   Jewelry: {
      Rings: ['Engagement Rings', 'Wedding Bands', 'Fashion Rings'],
      Necklaces: ['Chains', 'Pendants', 'Lockets'],
      Bracelets: ['Bangles', 'Charm Bracelets', 'Cuffs'],
      Earrings: ['Studs', 'Hoops', 'Drop Earrings'],
   },
   'Office Supplies': {
      'Office Electronics': ['Printers', 'Scanners', 'Laminators', 'Shredders'],
      Stationery: ['Notebooks', 'Pens', 'Markers', 'Sticky Notes'],
      'Office Furniture': ['Desks', 'Chairs', 'Filing Cabinets', 'Bookcases'],
      'Paper Products': ['Copy Paper', 'Envelopes', 'Notepads', 'Folders'],
   },
   'Pet Supplies': {
      Dogs: ['Dog Food', 'Dog Toys', 'Dog Beds', 'Leashes & Collars'],
      Cats: ['Cat Food', 'Litter Boxes', 'Scratching Posts', 'Cat Toys'],
      Birds: ['Bird Food', 'Cages', 'Perches', 'Toys'],
      Fish: ['Aquariums', 'Fish Food', 'Water Conditioners', 'Filters'],
   },
}
